name: Deploy React App to CloudFront

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: refs/heads/dev
            environment: development
          - branch: refs/heads/main
            environment: production
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: ./web
      run: npm ci

    - name: Conditional Branch Deployment
      if: ${{ github.ref == matrix.branch}}
      run: |
        echo "Deploying branch: ${{ matrix.branch }}"
        echo "Deploying to environment ${{ matrix.environment }}"
